CPU("hlt",              HLT,            0,  no_arguments_handler, func_without_arguments, hlt)
CPU("add",              ADD,            1,  no_arguments_handler, func_without_arguments, add)
CPU("sub",              SUB,            2,  no_arguments_handler, func_without_arguments, sub)
CPU("mul",              MUL,            3,  no_arguments_handler, func_without_arguments, mul)
CPU("div",              DIV,            4,  no_arguments_handler, func_without_arguments, div)
CPU("push",             PUSH,           5,  push_or_pop         , push_or_pop           , push)
CPU("pop",              POP,            6,  push_or_pop         , push_or_pop           , pop)
CPU("jmp",              JMP,            70, jumps               , jumps                 , jmp)
CPU("jb",               JB,             71, jumps               , jumps                 , jb)
CPU("jbe",              JBE,            72, jumps               , jumps                 , jbe)
CPU("ja",               JA,             73, jumps               , jumps                 , ja)
CPU("jae",              JAE,            74, jumps               , jumps                 , jae)
CPU("je",               JE,             75, jumps               , jumps                 , je)
CPU("jne",              JNE,            76, jumps               , jumps                 , jne)
CPU("call",             CALL,           77, jumps               , jumps                 , call)
CPU("pow",              POW,            8,  no_arguments_handler, func_without_arguments, pow)
CPU("fsqrt",            FSQRT,          9,  no_arguments_handler, func_without_arguments, fsqrt)
CPU("out",              OUT,            10, no_arguments_handler, func_without_arguments, out)
CPU("in",               IN,             11, no_arguments_handler, func_without_arguments, in)
CPU("nop",              NOP,            12, no_arguments_handler, func_without_arguments, nop)
CPU("draw_circle",      DRAW_CIRCLE,    13, no_arguments_handler, func_without_arguments, draw_circle)
CPU("open_draw",        OPEN_DRAW,      14, no_arguments_handler, func_without_arguments, open_draw)
CPU("draw",             DRAW,           15, no_arguments_handler, func_without_arguments, draw)
CPU("ret",              RET,            16, no_arguments_handler, func_without_arguments, ret)
