CPU("hlt",              HLT,    0,  no_arguments_handler, func_without_arguments, hlt)
CPU("add",              ADD,    1,  no_arguments_handler, func_without_arguments, add)
CPU("sub",              SUB,    2,  no_arguments_handler, func_without_arguments, sub)
CPU("mul",              MUL,    3,  no_arguments_handler, func_without_arguments, mul)
CPU("div",              DIV,    4,  no_arguments_handler, func_without_arguments, div)
CPU("push",             PUSH,   5,  push_or_pop         , func_with_one_argument, push)
CPU("pop",              POP,    6,  push_or_pop         , func_without_arguments, pop)
CPU("jmp",              JMP,    70, jumps               , func_with_one_argument, jmp)
CPU("jb",               JB,     71, jumps               , func_with_one_argument, jb)
CPU("jbe",              JBE,    72, jumps               , func_with_one_argument, jbe)
CPU("ja",               JA,     73, jumps               , func_with_one_argument, ja)
CPU("jae",              JAE,    74, jumps               , func_with_one_argument, jae)
CPU("je",               JE,     75, jumps               , func_with_one_argument, je)
CPU("jne",              JNE,    76, jumps               , func_with_one_argument, jne)
CPU("call",             CALL,   77, jumps               , func_with_one_argument, call)
CPU("pow",              POW,    8,  no_arguments_handler, func_without_arguments, pow)
CPU("fsqrt",            FSQRT,  9,  no_arguments_handler, func_without_arguments, fsqrt)
CPU("out",              OUT,    10, no_arguments_handler, func_without_arguments, out)
CPU("in",               IN,     11, no_arguments_handler, func_without_arguments, in)
CPU("ret",              RET,    12, no_arguments_handler, func_without_arguments, ret)
